version: "3.8"

networks:
  chanzit:

services:
  server:
    image: "nginx:stable-alpine"
    container_name: chanzit_server
    ports:
      - "8000:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - chanzit
    depends_on:
      - php
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: chanzit_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - chanzit
  npm:
    image: node:latest
    container_name: chanzit_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - chanzit
